### ISSUE TITLE
Registration form not submitting

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#21]
Some, or all, new registrations are failing to appear on the Registrar Dashboard. 

This may be a regression based on recent changes to price calculations.

**Comment by brylie** [comment]
@styrrell will you please help me reproduce this issue? What combination of registration details did you input when you notice this?

**Comment by brylie** [comment]
@styrrell I believe this bug is fixed. 

The server has been updated with the newest code, and the database was reset. Please verify that you can see registrants listed on the registrar dashboard, when logged in as the testing registrar.

**Comment by brylie** [comment]
I am closing this issue, as it seems to be fixed.

**Comment by styrrell** [comment]
I just tried this and again I am not seeing my registrations on the dashboard.
The email for my account is sarahtyrrell@alumnae.mills.edu.
I tried two test registrations: SarahTestApril12_01 Tyrrell and SarahTestApril12_02 Tyrrell.
Both 14 years old, full week, JYM housing.
When I click Register, nothing seems to happen. I do not see my registrations in the dashboard when I log in again as registrar@example.com.

**Comment by brylie** [comment]
OK, the registrations may not be submitting. I will troubleshoot this.

**Comment by brylie** [comment]
I think this was related to the recent 'grade in school' field. I had added conditional logic to display it only for people under 18, which was causing the form not to submit correctly.

**Comment by brylie** [comment]
I filed an [issue](https://github.com/aldeed/meteor-autoform/issues/878) with the upstream package.

**Comment by styrrell** [comment]
I think at this point, if this is blocking us, we can go ahead and have the grade in school appear for everyone. We need to get this completed!

**Comment by brylie** [comment]
I have already committed a fix for this, so am closing this issue.

**Comment by brylie** [comment]
I just double checked all commits, and finished fixing this. The field now shows for all registrants.

**Comment by brylie** [comment]
I will close this again, as it should be working.

**Comment by styrrell** [comment]
I just did a git pull to get the latest, and running locally I still see an issue when registering a 14 year old for JYM housing. It does not work.

**Comment by styrrell** [comment]
I did a git pull again just now to get the latest. I still see this issue running the latest locally.

**Comment by brylie** [comment]
OK, this issue is cropping up again. I am looking in to the underlying issue.

**Comment by brylie** [comment]
OK, I just enabled AutoForm.debug(), and got the following message:

``` javascript
Error in registration-form" "insert" Error: Fee must be an integer
```

**Comment by brylie** [comment]
I added code to make sure the fee calculation returns an integer. Please test.
